### ISSUE TITLE
Create a POST defaults / options file

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/core#38]
This file should ultimately be publicly accessible so that the UI can read it to get default post options for a server.  

Start by creating a JSON .in file that can be filled in on server population and then written to public location

* [x] Determine JSON schema needed
* [x] Create first version of JSON .in file
* [x] #51
* [x] Server install script generates public file

**Comment by cjgrady** [comment]
The .in file is located at LmServer/config/boom_post_defaults.json.in

Let's write the filled in file to LmWebServer/public_html/clients/boom_post_defaults.json

**Comment by cjgrady** [comment]
I included the default values that I had been using in comments at the end of each entry in the .in file in case those are useful.

**Comment by zzeppozz** [comment]
Do you still want this?  For now I hardcoded the default values, since this will seldom, if ever, be changed for individual rolls.  Let's discuss if it's still needed, the best location, and whether it be filled on install, or whether a script to change values would be useful.

**Comment by cjgrady** [comment]
Closing this as it seems to be fine as it is for the users actually doing this (me).  We can reopen if it becomes an issue later but our current direction seems to be moving away from this anyway.
